### ISSUE TITLE
Invalid user profile on fresh SB installation without Stripe

### ISSUE THREAD

**Issue by mkleszcz** [apptension/saas-boilerplate#180]
**Describe the bug**
On fresh SB installation when there is no Stripe configured the user register / login won't work because user profile is not created.

**To Reproduce**
1. Create new SB instance locally without Stripe env configuration1
2. Try to register and login

**Expected behavior**
The user should be able to register and login even if the app doesn't have Stripe integration enabled

**Comment by pmichalek-apptension** [comment]
Afaik it's not related to stripe, this migration code https://github.com/apptension/saas-boilerplate/blob/21dcdb9e6f2949ab45888a0cacd50fe5abd90f03/packages/backend/apps/users/migrations/0003_auto_20210716_1603.py#L9 doesn't create UserProfile along with the initial superuser instance. Fix on the way.
