### ISSUE TITLE
Update `dj-stripe` library in packages/backend to 2.7.x and stripe-mock docker image

### ISSUE THREAD

**Issue by pziemkowski** [apptension/saas-boilerplate#191]
**Is your feature request related to a problem? Please describe.**
There's a newer version of `dj-stripe` which has support for more payment methods.

There's also a newer version of `stripe-mock` docker image hosted in a different organisation. We should migrate.
I'm putting this information in the same ticket as probably new `dj-stripe` would need new API mock.

**Describe the solution you'd like**

**Additional context**
I tried updating myself but seems that a number of tests fail and it's not a quick drop-in change.

**Comment by pmichalek-apptension** [comment]
Release 2.8.0 has just emerged https://github.com/dj-stripe/dj-stripe/releases/tag/2.8.0 . Maybe @dsowinski2 can you take a look at updating that?
