### ISSUE TITLE
Decide if remove or clean styled-components theme

### ISSUE THREAD

**Issue by mkleszcz** [apptension/saas-boilerplate#230]
**Is your feature request related to a problem? Please describe.**
After migrate styles to Radix and Tailwind there will be unused code with the old theme based on styled-components. We should decide either remove it entirely or clean it and prepare for future usage in case of if someone in the future would like to use styled-components instead of tailwind styles.

**Additional context**
Related to #174

**Comment by kacperadler** [comment]
@mkleszcz do you think we can close this issue?
