### ISSUE TITLE
Password reset email is not sent

### ISSUE THREAD

**Issue by dciechowski** [apptension/saas-boilerplate#286]
**Describe the bug**
The user does not receive a reset password email.

**To Reproduce**
1. Go to the log in page
2. Click on the "Forgot password" button
3. Povide previously registered mail address
4. Click on the "Send the link" button 
5. Check the inbox of this mail address - **no mail comes**

**Expected behavior**
A password reset mail should be sent to the e-mail address provided earlier.

**Screenshots**
<img width="551" alt="image" src="https://github.com/apptension/saas-boilerplate/assets/137881691/1e1c0fdb-a136-4873-ba88-fdfd1bc855db">

**Comment by mkleszcz** [comment]
Messages are not received because of the AWS SES service in sandbox mode. After email verification it will work
