### ISSUE TITLE
Different avatars of one user in the notification widget

### ISSUE THREAD

**Issue by dciechowski** [apptension/saas-boilerplate#293]
**Describe the bug**
There is a capture of user data at the time of sending the notification. Please check if other personal data (other than avatar) are also unnecessarily captured.

**To Reproduce**
1. Log in as user A
2. Add an item X to the CRUD list
3. Log in as user B and set him an avatar
5. Edit the CRUD item X
6. Change again the avatar for user B on other
7. Edit again the CRUD item X
8. Log in as user A
9. Expand the notification widget - you can see 2 new notifications from user B with two different avatars.

**Expected behavior**
There should be displayed current user's avatar/data

**Screenshots**
![image](https://github.com/apptension/saas-boilerplate/assets/137881691/c5072ddd-1448-429a-9dcf-cc68dcac0454)

**Comment by bielsky0** [comment]
I think it is mainly related to the backend.

In the backend/apps/demo/notifications.py

an entry.edited_by.profile.avatar.thumbnail.url variable is sent as the notification avatar, which is a link to bucket
