### ISSUE TITLE
GraphQL versioning issue

### ISSUE THREAD

**Issue by rahuliitk** [apptension/saas-boilerplate#297]
**Describe the bug**
After I start the web app, it says that there are different versions of GraphQL. Below is the error : Failed to load schema from ../webapp-api-client/graphql/schema/api.graphql,../webapp-contentful/graphql/schema/contentful.graphql:
[FAILED] 
[FAILED]         Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.
[FAILED] 
[FAILED] Ensure that there is only one instance of "graphql" in the node_modules
[FAILED] directory. If different versions of "graphql" are the dependencies of other
[FAILED] relied on modules, use "resolutions" to ensure only one version is installed.
[FAILED] 
[FAILED] https://yarnpkg.com/en/docs/selective-version-resolutions
[FAILED] 
[FAILED] Duplicate "graphql" modules cannot be used at the same time since different
[FAILED] versions may have different capabilities and behavior. The data from one
[FAILED] version used in the function from another could produce confusing and
[FAILED] spurious results.
[FAILED]         Error: Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.
[FAILED] 
[FAILED] Ensure that there is only one instance of "graphql" in the node_modules
[FAILED] directory. If different versions of "graphql" are the dependencies of other
[FAILED] relied on modules, use "resolutions" to ensure only one version is installed.
[FAILED] 
[FAILED] https://yarnpkg.com/en/docs/selective-version-resolutions
[FAILED] 
[FAILED] Duplicate "graphql" modules cannot be used at the same time since different
[FAILED] versions may have different capabilities and behavior. The data from one
[FAILED] version used in the function from another could produce confusing and
[FAILED] spurious results.
[FAILED]     at instanceOf (/workspaces/saas-boilerplate/node_modules/.pnpm/graphql@14.7.0/node_modules/graphql/jsutils/instanceOf.js:28:13)
[FAILED]     at isSchema (/workspaces/saas-boilerplate/node_modules/.pnpm/graphql@14.7.0/node_modules/graphql/type/schema.js:36:34)
[FAILED]     at addResultOfCustomLoader (/workspaces/saas-boilerplate/node_modules/.pnpm/@graphql-tools+load@7.8.0_graphql@14.7.0/node_modules/@graphql-tools/load/cjs/load-typedefs/collect-sources.js:124:32)
[FAILED]     at /workspaces/saas-boilerplate/node_modules/.pnpm/@graphql-tools+load@7.8.0_graphql@14.7.0/node_modules/@graphql-tools/load/cjs/load-typedefs/collect-sources.js:195:13
[FAILED] 
[FAILED]         GraphQL Code Generator supports:
[FAILED]           - ES Modules and CommonJS exports (export as default or named export "schema")
[FAILED]           - Introspection JSON File
[FAILED]           - URL of GraphQL endpoint
[FAILED]           - Multiple files with type definitions (glob expression)
[FAILED]           - String in config file
[FAILED] 
[FAILED]         Try to use one of above options and run codegen again.
[FAILED] 
[FAILED]       
**To Reproduce**
1. pnpm install
2. nx run core:docker-compose:up
3. nx start webapp

**Expected behavior**
I expect localhost:3000 to show me a web app

**Screenshots**
502 Bad gateway when i type localhost:3000

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 

**Smartphone (please complete the following information):**
 - Device: Laptop

**Additional context**

**Comment by mkleszcz** [comment]
Hi @rahuliitk,

Thank you for reporting this issue. It should be fixed in the next release (or on latest master branch after merging #302).
Please note one thing when you starting up the application:
After running `make up` (or simply starting the docker containers) often there is some time needed for backend to be available and you need to wait couple of seconds for 502s to stop occur on localhost:3000
