### ISSUE TITLE
After clicking in the "Go back" button, the user should be moved to previously selected tab [Subscriptions page]

### ISSUE THREAD

**Issue by dciechowski** [apptension/saas-boilerplate#306]
**Describe the bug**
After clicking the "Go back" button, the user is always moved to the first tab, i.e. "Current subscription"

**To Reproduce**
1. Go to the Subscriptions page
2. Select i.e. "Transaction history" tab
3. Click on the "View transaction history" button
4. Click on the "Go back" button - the user is moved to the "Current subscription" tab

**Expected behavior**
The user should be moved again to the "Transaction history" tab.

**Screenshots**
<img width="1542" alt="image" src="https://github.com/apptension/saas-boilerplate/assets/137881691/f2778107-972b-4e8a-93b2-183ff89eb3c7">

**Comment by bielsky0** [comment]
The Back button correctly goes back to "/subscriptions", but there are tabs on the "/subscriptions" route that have an independent state from the route, and every time you return to "/subscriptions" the default tab will be displayed.

To display the correct tab, we could use the history package from react router and check if the previous path matches the selected bookmark

**Comment by mkleszcz** [comment]
Better solution would be to bind each tab to the url route
