### ISSUE TITLE
Subscription plans are duplicated

### ISSUE THREAD

**Issue by mkleszcz** [apptension/saas-boilerplate#320]
**Describe the bug**
There are duplicates in available plans.

**To Reproduce**
1. Log in as a user
2. Go to `Subscriptions` page
3. Click on `Edit subscription`
4. See duplicated plans

**Expected behavior**
Plans should not be duplicated. There should be only 3 different plans available.

**Comment by dsowinski2** [comment]
Can't reproduce for now. It seems that stripe API do not create new products when same name is provided, but return existing ones instead.
