### ISSUE TITLE
Sign-up returns validation error on fresh installation without env variables

### ISSUE THREAD

**Issue by mkleszcz** [apptension/saas-boilerplate#328]
### Describe the bug

After application setup using init script without any environment variables passed, there is no possibility to sign-up a new user on local machine because form throws a validation error: `Either subscription or price must be defiend`.

### Steps to reproduce

1. Call `npm init saas-boilerplate`
2. Run the app
3. Go to the sign up page
4. Try to register
5. See the error

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 15.36 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.4.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.12.1 - /usr/local/bin/npm
    pnpm: 8.6.1 - /usr/local/bin/pnpm
    Watchman: 2022.12.12.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/apptension/saas-boilerplate/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/apptension/saas-boilerplate/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://docs.demo.saas.apptoku.com/).
- [X] Check that there isn't [already an issue](https://github.com/apptension/saas-boilerplate/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/apptension/saas-boilerplate/discussions) or join our [Discord Chat Server](https://discord.gg/J6bz3BUQ).

**Comment by merry75** [comment]
@mkleszcz indeed just started without env variable, this should not block us to navigate and register

how to bypass this ?

**Comment by mkleszcz** [comment]
@merry75 For now you can create a Stripe account, add Stripe env variables and restart the app

**Comment by ValiDraganescu** [comment]
How to restart the app? Use `make up` or just restart the container?
