### ISSUE TITLE
App should go back to the sign in page after clicking on the "OK" button [signing in with Facebook ]

### ISSUE THREAD

**Issue by dciechowski** [apptension/saas-boilerplate#331]
### Describe the bug

After clicking on the OK button visible on the attached file the app should go back to the sign-in page:

<img width="778" alt="image" src="https://github.com/apptension/saas-boilerplate/assets/137881691/b38dc7f6-e7a9-4557-a4d5-6df8bcfbfb7a">

<img width="1728" alt="image" src="https://github.com/apptension/saas-boilerplate/assets/137881691/d9c3423a-c333-42d6-861e-a0813a4e2609">

### Steps to reproduce

Steps:
1. Go to the sign-in page
2. Click on the "Log in with Facebook" button - the info page with the Ok button was displayed
3. Click on the Ok button - **error page appears** 

Expected: After clicking on the OK button the app should go back to the sign-in page.

### System Info

```shell
Chrome, etc.
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/apptension/saas-boilerplate/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/apptension/saas-boilerplate/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://docs.demo.saas.apptoku.com/).
- [X] Check that there isn't [already an issue](https://github.com/apptension/saas-boilerplate/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/apptension/saas-boilerplate/discussions) or join our [Discord Chat Server](https://discord.apptension.com).

**Comment by dsowinski2** [comment]
This issue occurs only when DJANGO_DEBUG flag is enabled.

**Comment by mkleszcz** [comment]
I changed the flag on QA env so this should not be an issue anymore
