### ISSUE TITLE
Getting an error when new project is setup.

### ISSUE THREAD

**Issue by timeisgolden** [apptension/saas-boilerplate#344]
### Describe the bug

Hello, I am getting the following error when launcing `npm init sass-boilerplate`
below is the full error description.
`
Performing system check:
✔ Checking if docker is installed... it is!
✔ Checking if pnpm is installed... it is!
✔ Checking if nx is installed... it is!
    Error: Init directory must be empty!
npm ERR! code 1
npm ERR! path /Volumes/Work/Github/Marcus-Finley/nucleus
npm ERR! command failed
npm ERR! command sh -c create-saas-boilerplate

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/devteam/.npm/_logs/2023-07-21T10_48_01_997Z-debug-0.log
`
How I can solve this issue?

### Steps to reproduce

1. go to Terminal on Mac
2. launch the following command
    `npm init sass-boilerplate`

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 823.09 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    pnpm: 8.6.9 - ~/.nvm/versions/node/v16.14.2/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.2
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/apptension/saas-boilerplate/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/apptension/saas-boilerplate/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://docs.demo.saas.apptoku.com/).
- [X] Check that there isn't [already an issue](https://github.com/apptension/saas-boilerplate/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/apptension/saas-boilerplate/discussions) or join our [Discord Chat Server](https://discord.apptension.com).

**Comment by pziemkowski** [comment]
Hi,

The answer is right there in your log

`Error: Init directory must be empty!`

You're probably running the command in a directory that is not empty, but it should.

**Comment by timeisgolden** [comment]
@pziemkowski Thanks for your reply, 
I tried it in an empty directory but got the same error.

**Comment by pziemkowski** [comment]
Can you try this node script to see what it returns?

If it says `null` it means it didn't find any files in the directory. Maybe you have some hidden files there?
Just change the `'./init-dir'` to the directory you try to run the init script in.

```
const fs = require('fs').promises;

const directory = fs.opendir('./init-dir').then((directory) => {
    return directory.read().then((entry) => {
        console.log(entry)
    }).then(() => {
        directory.close()
    })
});
```

**Comment by timeisgolden** [comment]
Thanks, solved the issue, 
I found the git hidden files in my folder.
Thanks again.
