### ISSUE TITLE
./scripts/download-graphql-schema.sh: line 10: ./node_modules/.bin/rover: No such file or directory

### ISSUE THREAD

**Issue by pziemkowski** [apptension/saas-boilerplate#348]
### Describe the bug

Running `nx run webapp:graphql:download-schema` throws an error

```
./scripts/download-graphql-schema.sh: line 10: ./node_modules/.bin/rover: No such file or directory
```

### Steps to reproduce

1. Open root directory
2. Run `nx run webapp:graphql:download-schema`
3. Observe error

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 87.03 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: 8.6.1 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 114.0.5735.248
    Edge: 115.0.1901.183
    Safari: 16.3
  npmPackages:
    @apollo/client: ^3.7.9 => 3.7.9 
    @apollo/rover: ^0.12.2 => 0.12.2 
    @babel/preset-react: ^7.14.5 => 7.18.6 
    @graphql-typed-document-node/core: ^3.2.0 => 3.2.0 
    @nx/devkit: 16.3.2 => 16.3.2 
    @nx/eslint-plugin: 16.3.2 => 16.3.2 
    @nx/jest: 16.3.2 => 16.3.2 
    @nx/js: 16.3.2 => 16.3.2 
    @nx/linter: 16.3.2 => 16.3.2 
    @nx/node: 16.3.2 => 16.3.2 
    @nx/plugin: 16.3.2 => 16.3.2 
    @nx/react: 16.3.2 => 16.3.2 
    @nx/web: 16.3.2 => 16.3.2 
    @pmmmwh/react-refresh-webpack-plugin: ^0.5.7 => 0.5.10 
    @sb/core: * => 2.0.1 
    @svgr/webpack: ^6.1.2 => 6.5.1 
    @swc-node/register: ^1.4.2 => 1.5.5 
    @swc/cli: 0.1.62 => 0.1.62 
    @swc/core: ^1.2.173 => 1.3.27 
    @swc/helpers: 0.5.1 => 0.5.1 
    @tailwindcss/typography: ^0.5.9 => 0.5.9 
    @testing-library/react: 14.0.0 => 14.0.0 
    @types/gtag.js: ^0.0.12 => 0.0.12 
    @types/jest: 29.4.4 => 29.4.4 
    @types/node: 18.14.2 => 18.14.2 
    @types/react: 18.0.28 => 18.0.28 
    @types/react-dom: 18.0.11 => 18.0.11 
    @types/react-is: 17.0.3 => 17.0.3 
    @types/react-router-dom: 5.3.3 => 5.3.3 
    @types/styled-components: 5.1.26 => 5.1.26 
    @typescript-eslint/eslint-plugin: 5.59.9 => 5.59.9 
    @typescript-eslint/parser: 5.59.9 => 5.59.9 
    babel-jest: 29.4.3 => 29.4.3 
    babel-plugin-relay: ^14.1.0 => 14.1.0 
    babel-plugin-styled-components: 1.10.7 => 1.10.7 
    env-cmd: ^10.1.0 => 10.1.0 
    eslint: ^8.34.0 => 8.34.0 
    eslint-config-prettier: ^8.5.0 => 8.6.0 
    eslint-import-resolver-typescript: ^3.5.3 => 3.5.3 
    eslint-plugin-cypress: ^2.10.3 => 2.12.1 
    eslint-plugin-import: 2.27.5 => 2.27.5 
    eslint-plugin-jsx-a11y: 6.7.1 => 6.7.1 
    eslint-plugin-react: 7.32.2 => 7.32.2 
    eslint-plugin-react-hooks: 4.6.0 => 4.6.0 
    graphql: ^16.6.0 => 16.6.0 
    husky: ^8.0.0 => 8.0.3 
    jest: 29.4.3 => 29.4.3 
    jest-environment-jsdom: 29.4.3 => 29.4.3 
    jsonc-eslint-parser: ^2.1.0 => 2.1.0 
    lint-staged: ^10.5.4 => 10.5.4 
    nx: 16.3.2 => 16.3.2 
    nx-cloud: 16.0.5 => 16.0.5 
    prettier: ^2.6.2 => 2.8.3 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    react-is: 18.2.0 => 18.2.0 
    react-refresh: ^0.10.0 => 0.10.0 
    react-router-dom: 6.11.2 => 6.11.2 
    styled-components: 5.3.6 => 5.3.6 
    tailwindcss: ^3.3.2 => 3.3.2 
    tailwindcss-animate: ^1.0.5 => 1.0.5 
    ts-jest: 29.1.0 => 29.1.0 
    ts-node: 10.9.1 => 10.9.1 
    tsconfig-paths: ^4.1.2 => 4.1.2 
    tslib: ^2.3.0 => 2.4.1 
    typescript: 5.0.4 => 5.0.4 
    url-loader: ^4.1.1 => 4.1.1 
```
```


### Logs

```
egrep: .env: No such file or directory
./scripts/download-graphql-schema.sh: line 10: ./node_modules/.bin/rover: No such file or directory
./scripts/download-graphql-schema.sh: line 10: ./node_modules/.bin/rover: No such file or directory
Warning: run-commands command "/bin/sh ./scripts/download-graphql-schema.sh" exited with non-zero status code
 
 >  NX   Running target graphql for project webapp-contentful failed
   Failed tasks:
   
   - webapp-contentful:graphql:download-schema
   
   Hint: run the command with --verbose for more details.
> nx run webapp-api-client:graphql:generate-types
> @sb/webapp-api-client@2.0.1 graphql-codegen /Users/patrykziemkowski/PycharmProjects/saas-boilerplate-app/packages/webapp-libs/webapp-api-client
> graphql-codegen "-c" "./graphql/codegen.ts"
[STARTED] Parse Configuration
[SUCCESS] Parse Configuration
[STARTED] Generate outputs
[STARTED] Generate to src/graphql/__generated/gql/
[STARTED] Load GraphQL schemas
[SUCCESS] Load GraphQL schemas
[STARTED] Load GraphQL documents
[SUCCESS] Load GraphQL documents
[STARTED] Generate
[SUCCESS] Generate
[SUCCESS] Generate to src/graphql/__generated/gql/
[SUCCESS] Generate outputs
 
 >  NX   Successfully ran target graphql for project webapp-api-client
Warning: run-commands command "/bin/sh ./scripts/download-graphql-schema.sh" exited with non-zero status code
 
 >  NX   Running target graphql for project webapp-api-client failed
   Failed tasks:
   
   - webapp-api-client:graphql:download-schema
   
   Hint: run the command with --verbose for more details.
Warning: run-commands command "pnpm nx run webapp-api-client:graphql:download-schema" exited with non-zero status codeWarning: run-commands command "pnpm nx run webapp-contentful:graphql:download-schema" exited with non-zero status code

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target graphql for project webapp (4s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
 

```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/apptension/saas-boilerplate/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/apptension/saas-boilerplate/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://docs.demo.saas.apptoku.com/).
- [X] Check that there isn't [already an issue](https://github.com/apptension/saas-boilerplate/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/apptension/saas-boilerplate/discussions) or join our [Discord Chat Server](https://discord.apptension.com).

**Comment by ValiDraganescu** [comment]
I checked the `./node_modules/.bin/rover` in the app root and the binary is there
Maybe it's searching for it in the `node_modules` of the `webapp`? there is no `rover` there

**Comment by pziemkowski** [comment]
@ValiDraganescu I think the check for the VITE_CONTENTFUL_TOKEN is valid for a PR! Would be lovely if you can contribute.

I fixed the issue with `rover` in the PR linked above ^

**Comment by ValiDraganescu** [comment]
Thank you! As I said in the Discord channel, I think it would be better to add the correct path agains using the pnpm command as the later would force any user of the boilerplate to use pnpm?

**Comment by pziemkowski** [comment]
As of now, `pnpm` is a hard requirement to use SaaS Boilerplate. It would be too difficult for us to support all of them. 
We tried `npm workspaces` and as far as I remember they didn't work with our requirements. Can't really recall what it was but I just couldn't make it work. `pnpm` was the only one that worked well.
