### ISSUE TITLE
Can't build the solution 

### ISSUE THREAD

**Issue by sriwantha** [apptension/saas-boilerplate#385]
### Describe the bug

I am following the instructions given in https://docs.demo.saas.apptoku.com/getting-started/run-project/run-new-project

I then get an error like bellow and my containers are not starting

core: Warning: run-commands command "nx run-many --target=compose-build-image --projects=backend,workers" exited with non-zero status code
make: *** [Makefile.base.mk:37: up] Error 1

### Steps to reproduce

make up

### System Info

```shell
python --version 
Python 3.11.5

docker --version
Docker version 20.10.24, build 297e128

node --version
v18.17.1

pnpm --version
8.7.0

OS version
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
```

### Logs
The error log is attache below. 
[my-wellformatted-outputl.pdf](https://github.com/apptension/saas-boilerplate/files/12504750/my-wellformatted-outputl.pdf)

[sri-saas.txt](https://github.com/apptension/saas-boilerplate/files/12458562/sri-saas.txt)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/apptension/saas-boilerplate/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/apptension/saas-boilerplate/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://docs.demo.saas.apptoku.com/).
- [X] Check that there isn't [already an issue](https://github.com/apptension/saas-boilerplate/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/apptension/saas-boilerplate/discussions) or join our [Discord Chat Server](https://discord.apptension.com).

**Comment by pziemkowski** [comment]
So far, anything related to this problem that I found says you should reinstall your docker on your machine. 

When you look into logs it says something about permissions. 

Do you have a fresh docker installation? 
How did you install exactly?
Is is possible you used `snap` to install docker? I've seen this being given as a reason.

**Comment by sriwantha** [comment]
yes, I used snap to install docker. What's the other way I need to install docker on ubuntu to preven this happening?

**Comment by sriwantha** [comment]
Using your tip, I managed to get the docker build working. The snap installation of docker does not work. (as described here https://stackoverflow.com/questions/61876116/how-to-remove-a-snap-application-docker-completely) . 

A few missing steps. 
1. docker-compose (v1) has to be in place. Not docker compose (v2)
2. **docker volume create --name=saas-web-backend-db-data**  needs to be run before **Make up** command

I can see my containers are running but I can't access them through http://locahost:5001

**Comment by sriwantha** [comment]
got this working. I pruned all docker containers, images and volume then ran the steps with default values.
