### ISSUE TITLE
Unsupported browser detection

### ISSUE THREAD

**Issue by Balldoro** [apptension/saas-boilerplate#400]
### Describe the bug

Unsupported browser detection in current version doesn't work and breaks the application for many browsers, including new versions. If we use a browser which is not supported, the application doesn't load at all and we receive an error `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isCrawler')`. It happens on e.g. iPad Pro with iPadOS 16.4.1 both for Safari and Chrome. It also happens on Vivaldi browser on Windows. I also noticed that after selecting "ipad Air" device in Chrome dev tools and refreshing the page, the same thing happens
Besides this functionality not working, I don't think it should be applied to these browsers.

### Steps to reproduce

1. Open [any page of the app](https://app.demo.saas.apptoku.com/en/auth/login)
2. Open device toolbar inside Chrome dev tools
3. Select "ipad Air" dimensions
4. Reload the page
or 
1. Open SaaS boilerplate application on one of the iPads(real device or emulator)
<img width="1529" alt="Zrzut ekranu 2023-09-25 o 10 45 04" src="https://github.com/apptension/saas-boilerplate/assets/23015270/c2c2e371-b450-49de-a328-e9e53bd1b5a4">

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 63.00 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.0.1 - ~/.nvm/versions/node/v17.0.1/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v17.0.1/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v17.0.1/bin/npm
    pnpm: 8.6.0 - ~/.nvm/versions/node/v17.0.1/bin/pnpm
    Watchman: 2022.10.17.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.2
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/apptension/saas-boilerplate/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/apptension/saas-boilerplate/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://docs.demo.saas.apptoku.com/).
- [X] Check that there isn't [already an issue](https://github.com/apptension/saas-boilerplate/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/apptension/saas-boilerplate/discussions) or join our [Discord Chat Server](https://discord.apptension.com).

**Comment by pziemkowski** [comment]
I'll just remove the browser detection. I think that as of now, with evergreen browsers feature like this is not necessary.
