### ISSUE TITLE
Testbucket S3 not working

### ISSUE THREAD

**Issue by youngpake** [apptension/saas-boilerplate#413]
### Describe the bug

After uploading a document trying to view what has just been uploaded by clicking on it to this link I get:

Hmmm… can't reach this pageCheck if there is a typo in localstack.
Search the web for [localstack](https://www.bing.com/search?form=ANLKDR&q=localstack)
If spelling is correct, [try running Windows Network Diagnostics](javascript:diagnoseErrors()).
DNS_PROBE_FINISHED_NXDOMAIN

`http://[localstack](http://localstack:4566/test-bucket/documents/18f1dda89f8e3918/Photo-1.jpg?AWSAccessKeyId=foo&Signature=Tzoe67ok11MC9Xs%2B989mbbqjvc0%3D&Expires=1696408292):4566/test-bucket/documents/18f1dda89f8e3918/Photo-1.jpg?AWSAccessKeyId=foo&Signature=Tzoe67ok11MC9Xs%2B989mbbqjvc0%3D&Expires=1696408292`

### Steps to reproduce

1. From Sidebar click documents
2. Click or drag file to this area to upload
3. Upload document
4. Click on the uploaded document

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
    Memory: 2.82 GB / 15.80 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.8.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (117.0.2045.47)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @swc-node/register: ^1.6.8 => 1.6.8
    @swc/core: ^1.3.90 => 1.3.90
```

### Logs

DNS_PROBE_FINISHED_NXDOMAIN

### Validations

- [X] Follow our [Code of Conduct](https://github.com/apptension/saas-boilerplate/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/apptension/saas-boilerplate/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://docs.demo.saas.apptoku.com/).
- [X] Check that there isn't [already an issue](https://github.com/apptension/saas-boilerplate/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/apptension/saas-boilerplate/discussions) or join our [Discord Chat Server](https://discord.apptension.com).

**Comment by takahiroanno** [comment]
I also encountered the same bug. I think the problem is that "localstack" cannot be resolved on the host machine.

I don't know what the correct solution is, but in my case I added 
`127.0.0.1 localstack`
 to /private/etc/hosts on my mac and it works fine now.

**Comment by Crunchyman-ralph** [comment]
I think the solution would be to add localstack inside the network config of docker-compose.

Or just do localhost instead of localstack also works
