### ISSUE TITLE
Migration job fails to trigger on local deploy

### ISSUE THREAD

**Issue by gabrii** [apptension/saas-boilerplate#508]
### Describe the bug

When running `pnpm saas deploy`, the migration job fails to trigger as it can't resolve `localstack`.
This happens when `AWS_ENDPOINT_URL=http://localstack:4566` is present in `packages/backend/.env`, which is not needed anymore as that flag is being passes by `docker-compose.local.yml` now.

Therefore, it should be remove from `packages/backend/.env.shared`

### Steps to reproduce

1. Create a .env for backend based on .env.shared
2. pnpm saas build
3. pnpm saas deploy

### System Info

```
Any local deploy (not from CI) should face the same issue.
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/apptension/saas-boilerplate/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/apptension/saas-boilerplate/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://docs.demo.saas.apptoku.com/).
- [X] Check that there isn't [already an issue](https://github.com/apptension/saas-boilerplate/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/apptension/saas-boilerplate/discussions) or join our [Discord Chat Server](https://discord.apptension.com).

**Comment by mkleszcz** [comment]
Thank you for the contribution!:)
