### ISSUE TITLE
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@sb%2Finfra-core: Not Found - 404

### ISSUE THREAD

**Issue by tribanos** [apptension/saas-boilerplate#531]
### Describe the bug

I cant install the boilerplate. After pnpm install i get this error: " ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@sb%2Finfra-core: Not Found - 404"

Checked it in npmjs explorer and didnt find it. 

### Steps to reproduce

(ubuntu 22.04)

1. wget latest boilerplate release
2. tar xvfz..
3. cd into extracted folder
4. run command: pnpm install

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 14.57 GB / 15.59 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.12.2 - /usr/bin/node
    npm: 10.5.0 - /usr/bin/npm
    pnpm: 9.0.4 - /usr/local/bin/pnpm
```

### Logs

<details>
<summary>Click to see log!</summary>

```shell
pnpm install
packages/webapp                          |  WARN  The field "pnpm" was found in /home/podcraft/saas-boilerplate-2.6.0/packages/webapp/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.
Scope: all 22 workspace projects
/home/podcraft/saas-boilerplate-2.6.0/packages/backend:
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@sb%2Finfra-core: Not Found - 404

This error happened while installing a direct dependency of /home/podcraft/saas-boilerplate-2.6.0/packages/backend

@sb/infra-core is not in the npm registry, or you have no permission to fetch it.

No authorization header was set for the request.
Progress: resolved 7, reused 7, downloaded 0, added 0
```
</details>

### Validations

- [X] Follow our [Code of Conduct](https://github.com/apptension/saas-boilerplate/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/apptension/saas-boilerplate/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://docs.demo.saas.apptoku.com/).
- [X] Check that there isn't [already an issue](https://github.com/apptension/saas-boilerplate/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/apptension/saas-boilerplate/discussions) or join our [Discord Chat Server](https://discord.apptension.com).

**Comment by gabrii** [comment]
Your steps to reproduce are not supposed to work, you are missing the step to initialize the boilerplate:
```
pnpm create saas-boilerplate PATH
```
You should follow https://docs.demo.saas.apptoku.com/getting-started/run-project/run-new-project

**Comment by mkleszcz** [comment]
This is caused by the `pnpm` v9. Latest released version is not backward compatible and until we fix this I recommend to use pnpm 8
