### ISSUE TITLE
CLI is NOT respecting telemetry opt-out

### ISSUE THREAD

**Issue by bruteforks** [apptension/saas-boilerplate#587]
### Describe the bug

exporting SB_TELEMETRY_DISABLED=1 via zshrc and the CLI sends telemetry

`SB_TELEMETRY_DISABLED=1 pnpm saas command` and the CLI sends telemetry
even `SB_TELEMETRY_DISABLED=0 pnpm saas` still sends telemetry

### Steps to reproduce

Add your own honeycomb API key, and watch the telemetry data roll into honeycomb.io

![image](https://github.com/apptension/saas-boilerplate/assets/116930331/d5585e62-c46e-47b8-a7fa-581c1af86499)

![image](https://github.com/apptension/saas-boilerplate/assets/116930331/7689df6a-7cf8-485a-bd44-5c000023e49c)

### System Info

```shell
no thanks
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/apptension/saas-boilerplate/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/apptension/saas-boilerplate/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://docs.demo.saas.apptoku.com/).
- [X] Check that there isn't [already an issue](https://github.com/apptension/saas-boilerplate/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/apptension/saas-boilerplate/discussions) or join our [Discord Chat Server](https://discord.apptension.com).

**Comment by bruteforks** [comment]
Thanks for addressing it! Also [https://github.com/apptension/create-saas-boilerplate/](url) suffers from the same issue.

**Comment by bruteforks** [comment]
@mkleszcz Have you tested this? It's still not respecting user's preferences.

**Comment by mkleszcz** [comment]
@bruteforks yes, I have tested it and did it once again now. For me it's working as expected: when there is `SB_TELEMETRY_DISABLED` env variable set to `1` no data is sent and there is no info about telemetry. Are you sure that you pulled latest changes? If you are using create script this fix will be available on the latest release.
Also please do not duplicate issues. For the create script there is a separate repository with separate issues.
