### ISSUE TITLE
Remove codecommit from the stack as this service is deprecated for the new AWS accounts

### ISSUE THREAD

**Issue by mkleszcz** [apptension/saas-boilerplate#611]
### Describe the bug

Info from AWS:
https://repost.aws/questions/QUshILm0xbTjWJZSD8afYVgA/codecommit-cannot-create-a-repository

Codecommit service is deprecated for the new AWS accounts. We need to change the way we are triggering CI/CD pipeline.

### Steps to reproduce

1. Create new AWS account
2. Try to deploy CI/CD stack to the AWS

### System Info

```shell
.
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/apptension/saas-boilerplate/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/apptension/saas-boilerplate/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://docs.demo.saas.apptoku.com/).
- [X] Check that there isn't [already an issue](https://github.com/apptension/saas-boilerplate/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/apptension/saas-boilerplate/discussions) or join our [Discord Chat Server](https://discord.apptension.com).

**Comment by stefaluc** [comment]
@mkleszcz Do you have a recommended workaround for this issue? I have just run into this when running `pnpm saas infra deploy`:
```cli
CreateRepository request is not allowed because there is no existing repository in this AWS account or AWS Organization (Service: AWSCodeCommit; Status Code: 400; Error Code: OperationNotAllowedException; Request ID: 3cbb3638-14f3-49c1-b9cd-5153d50e1e58;
Proxy: null)
```

**Comment by stefaluc** [comment]
> @mkleszcz Do you have a recommended workaround for this issue? I have just run into this when running `pnpm saas infra deploy`:
> 
> ```
> CreateRepository request is not allowed because there is no existing repository in this AWS account or AWS Organization (Service: AWSCodeCommit; Status Code: 400; Error Code: OperationNotAllowedException; Request ID: 3cbb3638-14f3-49c1-b9cd-5153d50e1e58;
> Proxy: null)
> ```

If anyone is curious, I was able to bypass this issue by submitted a support request to AWS  asking for access to CodeCommit. There may have been a quicker way to do this, but I submitted a support case, which was then forwarded to the AWS service team. 

I needed to provide the following info:
- Region/s:
- Commercial Cloud, Gov Cloud, or CN?:
- Customer was a CodeCommit Customer prior to July 25th, 2024 via asking them:

This took some time and back and forth (~8 days), but eventually, they added me to the whitelist. Someone more persistent may get this done quicker.
