### ISSUE TITLE
Error deploying Redis Cluster

### ISSUE THREAD

**Issue by rickycousins** [apptension/saas-boilerplate#621]
### Describe the bug

On running pnpm saas infra deploy I get the following error:

saas-dev-MainStack | 16/43 | 11:50:25 | CREATE_FAILED        | AWS::ElastiCache::CacheCluster                | MainRedisCluster/CacheCluster (MainRedisClusterCacheCluster1B65F4FB) Cache Subnet Group saas-dev-main-redis does not exist. (Service: AmazonElastiCache; Status Code: 400; Error Code: CacheSubnetGroupNotFoundFault; Request ID: 20abb506-802c-4fdf-a063-60e04deb017b; Proxy: null)

### Steps to reproduce

Run pnpm saas infra deploy on a fresh account

### System Info

```shell
Tested on dev environment
```

### Logs

<details>
<summary>Click to expand!</summary>

```shell
genesis-dev-MainStack | 16/43 | 11:50:25 | CREATE_FAILED        | AWS::ElastiCache::CacheCluster                | MainRedisCluster/CacheCluster (MainRedisClusterCacheCluster1B65F4FB) Cache Subnet Group genesis-dev-main-redis does not exist. (Service: AmazonElastiCache; Status Code: 400; Error Code: CacheSubnetGroupNotFoundFault; Request ID: 20abb506-802c-4fdf-a063-60e04deb017b; Proxy: null)
```
</details>

### Validations

- [X] Follow our [Code of Conduct](https://github.com/apptension/saas-boilerplate/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/apptension/saas-boilerplate/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://docs.demo.saas.apptoku.com/).
- [X] Check that there isn't [already an issue](https://github.com/apptension/saas-boilerplate/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/apptension/saas-boilerplate/discussions) or join our [Discord Chat Server](https://discord.apptension.com).

**Comment by rickycousins** [comment]
Added a PR https://github.com/apptension/saas-boilerplate/pull/622

**Comment by stefaluc** [comment]
I just wanted to +1 that I also received this error, and #622 fixed it. Thanks @rickycousins!

**Comment by mkleszcz** [comment]
Merged:) Thank you for the contribution @rickycousins!
